# Generated by Django 2.2.3 on 2021-05-06 20:06

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(orders.models.OrderStatus('CREATED'), 'CREATED'), (orders.models.OrderStatus('PAYED'), 'PAYED'), (orders.models.OrderStatus('COMPLETED'), 'COMPLETED'), (orders.models.OrderStatus('CANCELED'), 'CANCELED')], default=orders.models.OrderStatus('CREATED'), max_length=50),
        ),
    ]
